spring.application.name=fitness-tracker-bff
spring.graphql.graphiql.enabled=true
spring.graphql.schema.locations=classpath:com/david/fitness_bff/contracts/

# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# PostgreSQL Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/trinity
spring.datasource.username=postgres
spring.datasource.password=your_secure_password

# Hibernate/JPA Settings (Tells Spring how to act with the schema)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true